default_platform(:ios)

platform :ios do
  desc "Build and deploy the iOS app"
  lane :build_and_deploy do
    # Update code signing settings
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./ios/App/App.xcodeproj",
      team_id: "TN748MMP9M",
      targets: ["App"],
      build_configurations: ["Debug", "Release"],
      code_sign_identity: "Apple Distribution: Velpuri Enterprises Inc. (TN748MMP9M)",
      profile_name: "Gen Style",
      bundle_identifier: "com.genstyle.app"
    )
    
    # Build the app
    build_ios_app(
      workspace: "./ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      export_options: "./exportOptions.plist"
    )
    
    # Upload to App Store Connect
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end
